"""create rebuilt core tables

Revision ID: bbd627449743
Revises: 
Create Date: 2026-07-20 22:20:57.210039
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = 'bbd627449743'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_created_at'), 'activity_logs', ['created_at'], unique=False)
    op.create_index('ix_activity_logs_target', 'activity_logs', ['target_type', 'target_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_target_type'), 'activity_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_title'), 'jobs', ['title'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('current_company', sa.String(length=200), nullable=True),
    sa.Column('current_title', sa.String(length=200), nullable=True),
    sa.Column('work_years', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='new', nullable=False),
    sa.Column('applied_job_id', sa.Integer(), nullable=True),
    sa.Column('resume_file_path', sa.String(length=500), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=True),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_applied_job_id'), 'candidates', ['applied_job_id'], unique=False)
    op.create_index(op.f('ix_candidates_education_level'), 'candidates', ['education_level'], unique=False)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_location'), 'candidates', ['location'], unique=False)
    op.create_index(op.f('ix_candidates_name'), 'candidates', ['name'], unique=False)
    op.create_index(op.f('ix_candidates_phone'), 'candidates', ['phone'], unique=False)
    op.create_index(op.f('ix_candidates_source'), 'candidates', ['source'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_index(op.f('ix_candidates_work_years'), 'candidates', ['work_years'], unique=False)
    op.create_table('education',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('school', sa.String(length=200), nullable=True),
    sa.Column('degree', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('is_985', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_211', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_candidate_id'), 'education', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_education_degree'), 'education', ['degree'], unique=False)
    op.create_index(op.f('ix_education_school'), 'education', ['school'], unique=False)
    op.create_table('project_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('achievements', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_experience_candidate_id'), 'project_experience', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_project_experience_project_name'), 'project_experience', ['project_name'], unique=False)
    op.create_table('resumes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_type', sa.String(length=30), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.String(length=30), server_default='uploaded', nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parsed_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_candidate_id'), 'resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_resumes_job_id'), 'resumes', ['job_id'], unique=False)
    op.create_index(op.f('ix_resumes_parse_status'), 'resumes', ['parse_status'], unique=False)
    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('hard_pass', sa.Boolean(), nullable=True),
    sa.Column('skill_score', sa.Integer(), nullable=True),
    sa.Column('experience_score', sa.Integer(), nullable=True),
    sa.Column('project_score', sa.Integer(), nullable=True),
    sa.Column('strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.String(length=20), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('raw_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_screening_candidate_job')
    )
    op.create_index(op.f('ix_screening_results_candidate_id'), 'screening_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_screening_results_job_id'), 'screening_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_screening_results_overall_score'), 'screening_results', ['overall_score'], unique=False)
    op.create_index(op.f('ix_screening_results_recommendation'), 'screening_results', ['recommendation'], unique=False)
    op.create_table('work_experience',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('start_date', sa.String(length=20), nullable=True),
    sa.Column('end_date', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tech_stack', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_experience_candidate_id'), 'work_experience', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_work_experience_company'), 'work_experience', ['company'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('screening_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('report_type', sa.String(length=20), server_default='screening', nullable=False),
    sa.Column('format', sa.String(length=20), server_default='markdown', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['screening_id'], ['screening_results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_candidate_id'), 'reports', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_reports_job_id'), 'reports', ['job_id'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reports_screening_id'), 'reports', ['screening_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_screening_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index(op.f('ix_reports_job_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_candidate_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_work_experience_company'), table_name='work_experience')
    op.drop_index(op.f('ix_work_experience_candidate_id'), table_name='work_experience')
    op.drop_table('work_experience')
    op.drop_index(op.f('ix_screening_results_recommendation'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_overall_score'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_job_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_candidate_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_resumes_parse_status'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_job_id'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_candidate_id'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_project_experience_project_name'), table_name='project_experience')
    op.drop_index(op.f('ix_project_experience_candidate_id'), table_name='project_experience')
    op.drop_table('project_experience')
    op.drop_index(op.f('ix_education_school'), table_name='education')
    op.drop_index(op.f('ix_education_degree'), table_name='education')
    op.drop_index(op.f('ix_education_candidate_id'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_candidates_work_years'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_source'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_phone'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_location'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_education_level'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_applied_job_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_jobs_title'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_target_type'), table_name='activity_logs')
    op.drop_index('ix_activity_logs_target', table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_created_at'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
