"""External provider adapters."""

from app.adapters.resume_structure import (
    DeepSeekResumeStructureAdapter,
    ResumeStructureAdapterError,
    ResumeStructureAdapterResult,
    ResumeStructureAuthenticationError,
    ResumeStructureConfigurationError,
    ResumeStructureEmptyResponseError,
    ResumeStructureInputError,
    ResumeStructureQuotaError,
    ResumeStructureRateLimitError,
    ResumeStructureResponseInterruptedError,
    ResumeStructureServiceUnavailableError,
    ResumeStructureTimeoutError,
    ResumeStructureUpstreamError,
)
from app.adapters.screening_rubric_generation import (
    DeepSeekRubricGenerationAdapter,
    RubricGenerationAdapterError,
    RubricGenerationAdapterResult,
    RubricGenerationConfigurationError,
    RubricGenerationTimeoutError,
)
from app.adapters.screening_model import (
    SCREENING_MODEL_CONFIG_VERSION,
    DeepSeekScreeningModelAdapter,
    ScreeningModelAdapterError,
    ScreeningModelAdapterResult,
    ScreeningModelConfigurationError,
    ScreeningModelInputError,
    ScreeningModelTimeoutError,
)

__all__ = [
    "DeepSeekResumeStructureAdapter",
    "DeepSeekRubricGenerationAdapter",
    "DeepSeekScreeningModelAdapter",
    "RubricGenerationAdapterError",
    "RubricGenerationAdapterResult",
    "RubricGenerationConfigurationError",
    "RubricGenerationTimeoutError",
    "SCREENING_MODEL_CONFIG_VERSION",
    "ScreeningModelAdapterError",
    "ScreeningModelAdapterResult",
    "ScreeningModelConfigurationError",
    "ScreeningModelInputError",
    "ScreeningModelTimeoutError",
    "ResumeStructureAdapterError",
    "ResumeStructureAdapterResult",
    "ResumeStructureAuthenticationError",
    "ResumeStructureConfigurationError",
    "ResumeStructureEmptyResponseError",
    "ResumeStructureInputError",
    "ResumeStructureQuotaError",
    "ResumeStructureRateLimitError",
    "ResumeStructureResponseInterruptedError",
    "ResumeStructureServiceUnavailableError",
    "ResumeStructureTimeoutError",
    "ResumeStructureUpstreamError",
]
